[versions]
aapt2Proto = "8.1.4-10154469"
accompanist = "0.37.0"
# AGP and tools should be updated together
androidGradlePlugin = "8.13.0"
androidTools = "31.13.0"
androidxActivity = "1.10.1"
androidxAnnotation = "1.9.1"
androidxAppCompat = "1.7.0"
androidxComposeBom = "2026.01.01"
#androidxComposeFoundation = "1.8.0-alpha07"
androidxComposeMaterial3 = "1.5.0-alpha13"
androidxCore = "1.15.0"
androidxCoreSplashScreen = "1.0.1"
androidxDataStore = "1.1.4"
androidxEspresso = "3.6.1"
androidxHiltNavigationCompose = "1.2.0"
androidxLifecycle = "2.8.7"
androidxNavigation = "2.8.9"
androidxTestCore = "1.6.1"
androidxTestExt = "1.2.1"
androidxTestRules = "1.6.1"
androidxTestRunner = "1.6.2"
androidxWindowManager = "1.3.0"
androidxWork = "2.10.0"
ant = "1.10.14"
apacheCommonsLang3 = "3.13.0"
apacheCommonsCompress = "1.24.0"
apksig = "8.1.4"
apkzlib = "8.1.4"
asm = "9.6"
coil = "2.6.0"
commonsIo = "2.14.0"
fastutil = "8.5.12"
firebaseBom = "33.7.0"
firebaseCrashlyticsPlugin = "3.0.6"
gmsPlugin = "4.4.2"
groovy = "5.0.0-alpha-2"
gson = "2.10.1"
guava = "33.0.0-jre"
hilt = "2.56"
hiltExt = "1.2.0"
jansi = "2.4.1"
jatl = "0.2.3"
javaxInject = "1"
junit4 = "4.13.2"
kotlin = "2.2.20"
kotlinxCoroutines = "1.10.1"
kotlinxDatetime = "0.6.1"
kotlinxSerializationJson = "1.8.1"
ksp = "2.3.1"
# TODO: Update this dependency once https://github.com/firebase/firebase-android-sdk/issues/5997 is fixed
protobuf = "4.26.1"
#protobufJava = "4.0.0-rc-2"
protobufPlugin = "0.9.4"
room = "2.7.2"
slf4j = "2.0.9"
zipflinger = "8.2.0"

[bundles]
androidx-compose-ui-test = ["androidx-compose-ui-test", "androidx-compose-ui-testManifest"]

[libraries]
accompanist-adaptive = { group = "com.google.accompanist", name = "accompanist-adaptive", version.ref = "accompanist" }
#accompanist-systemuicontroller = { group = "com.google.accompanist", name = "accompanist-systemuicontroller", version.ref = "accompanist" }
#accompanist-testharness = { group = "com.google.accompanist", name = "accompanist-testharness", version.ref = "accompanist" }
android-signflinger = { group = "com.android", name = "signflinger", version.ref = "signflinger" }
android-zipflinger = { group = "com.android", name = "zipflinger", version.ref = "zipflinger" }
android-tools-annotations = { group = "com.android.tools", name = "annotations", version.ref = "androidTools" }
android-tools-build-aapt2-proto = { group = "com.android.tools.build", name = "aapt2-proto", version.ref = "aapt2Proto" }
android-tools-build-apksig = { group = "com.android.tools.build", name = "apksig", version.ref = "apksig" }
android-tools-build-apkzlib = { group = "com.android.tools.build", name = "apkzlib", version.ref = "apkzlib" }
android-tools-common = { group = "com.android.tools", name = "common", version.ref = "androidTools" }
android-tools-layoutlib = { group = "com.android.tools.layoutlib", name = "layoutlib-api", version.ref = "androidTools" }
android-tools-r8 = { group = "com.android.tools", name = "r8", version.ref = "r8" }
android-tools-sdk-common = { group = "com.android.tools", name = "sdk-common", version.ref = "androidTools" }
android-tools-sdklib = { group = "com.android.tools", name = "sdklib", version.ref = "androidTools" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidxActivity" }
androidx-annotation = { group = "androidx.annotation", name = "annotation", version.ref = "androidxAnnotation" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidxAppCompat" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "androidxComposeBom" }
androidx-compose-foundation = { group = "androidx.compose.foundation", name = "foundation" }
androidx-compose-foundation-layout = { group = "androidx.compose.foundation", name = "foundation-layout" }
androidx-compose-material-iconsExtended = { group = "androidx.compose.material", name = "material-icons-extended" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "androidxComposeMaterial3" }
androidx-compose-material3-navigationSuite = { group = "androidx.compose.material3", name = "material3-adaptive-navigation-suite" }
androidx-compose-material3-adaptive = { group = "androidx.compose.material3.adaptive", name = "adaptive" }
androidx-compose-material3-adaptive-layout = { group = "androidx.compose.material3.adaptive", name = "adaptive-layout" }
androidx-compose-material3-adaptive-navigation = { group = "androidx.compose.material3.adaptive", name = "adaptive-navigation" }
androidx-compose-material3-windowSizeClass = {group = "androidx.compose.material3", name = "material3-window-size-class" }
androidx-compose-runtime = { group = "androidx.compose.runtime", name = "runtime" }
androidx-compose-runtime-livedata = { group = "androidx.compose.runtime", name = "runtime-livedata" }
androidx-compose-ui-test = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-ui-testManifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-util = { group = "androidx.compose.ui", name = "ui-util" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidxCore" }
androidx-core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "androidxCoreSplashScreen" }
androidx-dataStore-core = { group = "androidx.datastore", name = "datastore", version.ref = "androidxDataStore" }
#androidx-dataStore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "androidxDataStore" }
androidx-hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "androidxHiltNavigationCompose" }
#androidx-lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "androidxLifecycle" }
androidx-lifecycle-runtimeCompose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidxLifecycle" }
androidx-lifecycle-viewModelCompose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "androidxLifecycle" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "androidxNavigation" }
androidx-navigation-testing = { group = "androidx.navigation", name = "navigation-testing", version.ref = "androidxNavigation" }
androidx-test-core = { group = "androidx.test", name = "core", version.ref = "androidxTestCore" }
androidx-test-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidxEspresso" }
androidx-test-ext = { group = "androidx.test.ext", name = "junit-ktx", version.ref = "androidxTestExt" }
androidx-test-rules = { group = "androidx.test", name = "rules", version.ref = "androidxTestRules" }
androidx-test-runner = { group = "androidx.test", name = "runner", version.ref = "androidxTestRunner" }
androidx-window-core = { group = "androidx.window", name = "window-core", version.ref = "androidxWindowManager"}
androidx-work-ktx = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "androidxWork" }
androidx-work-testing = { group = "androidx.work", name = "work-testing", version.ref = "androidxWork" }
ant = { group = "org.apache.ant", name = "ant", version.ref = "ant" }
apache-commons-lang3 = { group = "org.apache.commons", name = "commons-lang3", version.ref = "apacheCommonsLang3" }
apache-commons-compress = { group = "org.apache.commons", name = "commons-compress", version.ref = "apacheCommonsCompress" }
asm = { group = "org.ow2.asm", name = "asm", version.ref = "asm" }
asm-tree = { group = "org.ow2.asm", name = "asm-tree", version.ref = "asm" }
asm-commons = { group = "org.ow2.asm", name = "asm-commons", version.ref = "asm" }
coil-kt = { group = "io.coil-kt", name = "coil", version.ref = "coil" }
coil-kt-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }
coil-kt-svg = { group = "io.coil-kt", name = "coil-svg", version.ref = "coil" }
commons-io = { group = "commons-io", name = "commons-io", version.ref = "commonsIo" }
fastutil = { group = "it.unimi.dsi", name = "fastutil", version.ref = "fastutil" }
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics" }
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref="firebaseBom" }
firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics" }
firebase-firestore-ktx = { group = "com.google.firebase", name = "firebase-firestore-ktx" }
groovy = { group = "org.apache.groovy", name = "groovy", version.ref = "groovy" }
groovy-ant = { group = "org.apache.groovy", name = "groovy-ant", version.ref = "groovy" }
groovy-json = { group = "org.apache.groovy", name = "groovy-json", version.ref = "groovy" }
groovy-templates = { group = "org.apache.groovy", name = "groovy-templates", version.ref = "groovy" }
groovy-xml = { group = "org.apache.groovy", name = "groovy-xml", version.ref = "groovy" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
guava = { group = "com.google.guava", name = "guava", version.ref = "guava" }
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-android-testing = { group = "com.google.dagger", name = "hilt-android-testing", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }
hilt-ext-compiler = { group = "androidx.hilt", name = "hilt-compiler", version.ref = "hiltExt" }
hilt-ext-work = { group = "androidx.hilt", name = "hilt-work", version.ref = "hiltExt" }
jansi = { group = "org.fusesource.jansi", name = "jansi", version.ref = "jansi" }
jatl = { group = "com.googlecode.jatl", name = "jatl", version.ref = "jatl" }
javax-inject = { group = "javax.inject", name = "javax.inject", version.ref = "javaxInject" }
junit4 = { group = "junit", name = "junit", version.ref = "junit4" }
jsr305 = { group = "com.google.code.findbugs", name = "jsr305", version.ref = "jsr305" }
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-guava", version.ref = "kotlinxCoroutines" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlinxCoroutines" }
kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "kotlinxDatetime" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
kryo = { group = "com.esotericsoftware", name = "kryo", version.ref = "kryo" }
native-platform = { group = "net.rubygrapefruit", name = "native-platform", version.ref = "nativePlatform" }
native-platform-file-events = { group = "net.rubygrapefruit", name = "file-events", version.ref = "nativePlatform" }
#protobuf-java = { group = "com.google.protobuf", name = "protobuf-java", version.ref = "protobufJava" }
#protobuf-java-protoc = { group = "com.google.protobuf", name = "protoc", version.ref = "protobufJava" }
protobuf-kotlin-lite = { group = "com.google.protobuf", name = "protobuf-kotlin-lite", version.ref = "protobuf" }
protobuf-protoc = { group = "com.google.protobuf", name = "protoc", version.ref = "protobuf" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
slf4j = { group = "org.slf4j", name = "slf4j-api", version.ref = "slf4j" }

# Dependencies of the included build-logic
android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "androidGradlePlugin" }
compose-gradlePlugin = { module = "org.jetbrains.kotlin:compose-compiler-gradle-plugin", version.ref = "kotlin" }
firebase-crashlytics-gradlePlugin = { group = "com.google.firebase", name = "firebase-crashlytics-gradle", version.ref = "firebaseCrashlyticsPlugin" }
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
ksp-gradlePlugin = { group = "com.google.devtools.ksp", name = "com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }
room-gradlePlugin = { group = "androidx.room", name = "room-gradle-plugin", version.ref = "room" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
android-test = { id = "com.android.test", version.ref = "androidGradlePlugin" }
compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebaseCrashlyticsPlugin" }
gms = { id = "com.google.gms.google-services", version.ref = "gmsPlugin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
protobuf = { id = "com.google.protobuf", version.ref = "protobufPlugin" }
room = { id = "androidx.room", version.ref = "room" }

# Plugins defined by this project
androlabs-android-application = { id = "androlabs.android.application", version = "unspecified" }
androlabs-android-application-compose = { id = "androlabs.android.application.compose", version = "unspecified" }
androlabs-android-application-firebase = { id = "androlabs.android.application.firebase", version = "unspecified" }
androlabs-android-application-flavors = { id = "androlabs.android.application.flavors", version = "unspecified" }
androlabs-android-feature = { id = "androlabs.android.feature", version = "unspecified" }
androlabs-android-hilt = { id = "androlabs.android.hilt", version = "unspecified" }
androlabs-android-library = { id = "androlabs.android.library", version = "unspecified" }
androlabs-android-library-compose = { id = "androlabs.android.library.compose", version = "unspecified" }
androlabs-android-room = { id = "androlabs.android.room", version = "unspecified" }
androlabs-android-test = { id = "androlabs.android.test", version = "unspecified" }
androlabs-jvm-library = { id = "androlabs.jvm.library", version = "unspecified" }
